### ISSUE TITLE
MacOS : dlopen ( gpivpi.vpl, 0x0009): symbol not found in flat namespace '_PyErr_Print'. #3018

### ISSUE THREAD

**Issue by TomO700** [icarus-sim/icarus#26] opened 2022-06-30 20:37 UTC
I am trying to run icarus with cocotb and get the following error. Due to 'vpl' I was thinking its probably coming from icarus. 
Can someone please help

```
/opt/homebrew/bin/vvp -M /opt/homebrew/lib/python3.9/site-packages/cocotb/share/makefiles/build/libs/arm64 -m gpivpi sim_build/sim.vvp   
gpivpi:`/opt/homebrew/lib/python3.9/site-packages/cocotb/share/makefiles/build/libs/arm64/gpivpi.vpl' failed to open using dlopen() because:
    dlopen(/opt/homebrew/lib/python3.9/site-packages/cocotb/share/makefiles/build/libs/arm64/gpivpi.vpl, 0x0009): symbol not found in flat namespace '_PyErr_Print'.
```

thanks

**Comment by lorenzosaino** [comment] 2022-07-01 10:58
Hi Tom, 

Thanks for reporting the issue. 

Could you please elaborate more on why you think this is an icarus issue? From the output you pasted I see you're running a `vvp` binary (which is not part of Icarus codebase), you pass as argument the path to the `cocotb` (which is not part of icarus or a dependency of icarus, and I checked it doesn't have icarus as dependency) and the error message doesn't refer to icarus. So I am not sure how icarus might have to do with it.

Is it possible that you might be looking at a different icarus library, like https://github.com/bretonr/Icarus?

**Comment by lorenzosaino** [comment] 2022-07-08 15:23
I am closing this issue for now. If you still have issues and believe are caused by this project, please feel free to reopen it.

**Closed by lorenzosaino** 2022-07-08 15:23 UTC
