### ISSUE TITLE
Support for assign statements

### ISSUE THREAD

**Issue by TomO700** [icarus-sim/icarus#28] opened 2022-07-03 01:59 UTC
Hi,

May I check whether you have a limitation on assign statements for version 0.9.7 and 0.9.8 of icarus?
Seems like assigns work only when constant values are assigned.

Thanks

**Comment by lorenzosaino** [comment] 2022-07-08 15:23
Closing this issue since it is a duplicate of https://github.com/icarus-sim/icarus/issues/27.

**Closed by lorenzosaino** 2022-07-08 15:23 UTC
